MVC_Produccion/Controllers/BandejasController.cs
using AccesoDatos.Contexto.Produccion;
using MVC_Produccion.Sesiones;
using Servicios.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace MVC_Produccion.Controllers
{
    public class BandejasController : Controller
    {
        private IBandejaServicio BandejaServicio;
        private IBaseServicio<OpcionesTrabajo> OpcionesTrabajoPermisos;

        private OpcionesTrabajo Configuraciones;

        public BandejasController(IBandejaServicio _bandejaServicio, IBaseServicio<OpcionesTrabajo> _opcionesTrabajo)
        {
            this.OpcionesTrabajoPermisos = _opcionesTrabajo;
            this.BandejaServicio = _bandejaServicio;
            this.Configuraciones = this.OpcionesTrabajoPermisos.Obtener().FirstOrDefault();

        }
        // GET: Bandejas
        public ActionResult Index()
        {
            List<SelectListItem> ListadoEstados = new List<SelectListItem>()
                            {
                                new SelectListItem() {Text="No Historica", Value="false"},
                                new SelectListItem() {Text="Historica", Value="true"}
                            };

            ViewBag.ListadoEstados = ListadoEstados;
            return View();
        }
        public ActionResult ObtenerInformacion(bool Historicas = false)
        {
            var lista = this.BandejaServicio.Obtener(Historicas);
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
       
        // GET: Bandejas/Create
        public ActionResult AddOrEdit(int idMovimiento)
        {
            MovimientosBandejas mov = new MovimientosBandejas() {Fecha = DateTime.Today };
            try
            {
                if (idMovimiento != 0)
                    mov = this.BandejaServicio.ObtenerPorId(idMovimiento);
            }
            catch (Exception)
            {

            }
            return View(mov);
        }
        [HttpPost]
        public ActionResult AddOrEdit(MovimientosBandejas movimiento)
        {
            using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled)) 
            {             
                try
                {
                    if (this.BandejaServicio.ExisteMovimiento(movimiento.CodigoMovimiento,movimiento.Prefijo,movimiento.NroComprobante))
                        return Json(new { success = false, mensaje ="Combinacion de Prefijo y Comprobante ya cargada."}, JsonRequestBehavior.AllowGet);

                    var mensaje = "Se agrego correctamente";
                    if (movimiento.Detalles == null)
                    {
                        mensaje = "Por favor, agregue un Insumo";
                        return Json(new { success = false, mensaje }, JsonRequestBehavior.AllowGet);
                    }
                    if (movimiento.CodigoMovimiento == 0)
                        this.BandejaServicio.Agregar(movimiento);
                    else
                    {
                        foreach (var item in movimiento.Detalles)
                        {
                            item.CodigoMovimiento = movimiento.CodigoMovimiento;
                        }
                        this.BandejaServicio.Editar(movimiento.CodigoMovimiento,movimiento.Fecha,movimiento.Origen,movimiento.Destino.Value,movimiento.Prefijo, movimiento.NroComprobante, movimiento.Detalles.ToList());
                        mensaje = "Se edito Correctamente";

                    }
                    scope.Complete();
                    return Json(new { success= true,mensaje }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json(new { success = false, mensaje = ex.Message}, JsonRequestBehavior.AllowGet);
                }
            }
        } 

    
        public ActionResult Delete(int id)
        {
            using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    // TODO: Add delete logic here
                    this.BandejaServicio.BorrarPorId(id);
                    scope.Complete();
                    return Json(new { success = true}, JsonRequestBehavior.AllowGet);

                }
                catch (Exception ex)
                {
                    return Json(new { success = false, mensaje = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
        public ActionResult Actualizar(List<int> codigos)
        {
            using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    foreach (var c in codigos)
                    {
                        this.BandejaServicio.PasarHistorico(c);
                    }
                    scope.Complete();
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json(new { success = false, mensaje = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
        public ActionResult TablaBandejas(string parametroPost, int codigoExpedicion = 0, int codigoMovimiento = 0,bool soloLectura = false)
        {
            ViewBag.soloLectura = soloLectura;
            List<DetallesMovimientosBandejas> lista;
            if (codigoExpedicion != 0)
                lista = this.BandejaServicio.ObtenerDetallesPorIdExpedicion(codigoExpedicion);
            else
                lista = this.BandejaServicio.ObtenerDetallesPorId(codigoMovimiento);

            ViewBag.parametroPost = parametroPost;

            return PartialView(lista);
        }
    }
}

MVC_Produccion/Views/Bandejas/AddOrEdit.cshtml
@model AccesoDatos.Contexto.Produccion.MovimientosBandejas
@{
    Layout = null;
}
<div class="modal-body modalCreate" style="padding: 0px">
    @using (Html.BeginForm("AddOrEdit", "Bandejas", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "formAddOrEdit", autocomplete = "off" }))
    {
        @Html.HiddenFor(model => model.Historico)
        @Html.HiddenFor(model => model.CodigoMovimiento)
        @Html.HiddenFor(model => model.Codigo_Interno_Expedicion)

    <div class="col-md-12 caja-contenedora flexible2">
        <div class="col-md-12 caja-sector-modal">
            <div class="col-md-3">
                <div class="col-md-3" style="padding-right:10px!important;">
                    @Html.Label("Fecha:", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control", @type = "text", @style = "text-align:right;display:inline-block;" } })
                </div>
            </div>
            <div class="col-md-4 form-medio">
                <div class="col-md-8">
                    @Html.Label("Sucursal Origen:", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-4 input-group">
                    @Html.EditorFor(model => model.Origen, new { htmlAttributes = new { @class = "form-control", type = "text" } })
                    <span class="input-group-addon" style="max-height:25px;padding:3px 12px;"><a href="#" onclick="AbrirModalSucursales('Origen')" id="Lupa_Origen"><span class="glyphicon glyphicon-search"></span></a></span>
                </div>
            </div>
            <div class="col-md-4 form-medio">
                <div class="col-md-9">
                    @Html.Label("Sucursal Destino:", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-3 input-group">
                    @Html.EditorFor(model => model.Destino, new { htmlAttributes = new { @class = "form-control", type = "text" } })
                    <span class="input-group-addon" style="max-height:25px;padding:3px 12px;"><a href="#" onclick="AbrirModalSucursales('Destino')"><span class="glyphicon glyphicon-search"></span></a></span>
                </div>
            </div>

        </div>
        <div class="col-md-12 caja-sector-modal">
            <div class="col-md-3 form-medio">
                <div class="col-md-4 form-medio">
                    @Html.LabelFor(model => model.Prefijo, "Prefijo", new { @class = "control-label" })
                </div>
                <div class="col-md-6 form-medio">
                    @Html.EditorFor(model => model.Prefijo, new { htmlAttributes = new { @class = "form-control", @style = "text-align:right" } })
                    @Html.ValidationMessageFor(model => model.Prefijo)
                </div>
            </div>
            <div class="col-md-5 form-medio">
                <div class="col-md-7 form-medio">
                    @Html.LabelFor(model => model.NroComprobante, "Número de Comprobante", new { @class = "control-label" })
                </div>
                <div class="col-md-4 form-medio">
                    @Html.EditorFor(model => model.NroComprobante, new { htmlAttributes = new { @class = "form-control", @style = "text-align:right" } })
                    @Html.ValidationMessageFor(model => model.NroComprobante)
                </div>
            </div>
        </div>
        <div class="col-md-12 caja-contenedora">
            @{Html.RenderAction("TablaBandejas", "Bandejas", new { parametroPost = "Detalles", codigoMovimiento = Model.CodigoMovimiento });}
        </div>
    </div>
 
        <div class="modal-footer modalCreate">
            <button type="button" onclick="EnviarFormulario($('#formAddOrEdit'))" class="btn btn-primary">Confirmar</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
    }
</div>

<script>
    if ($('#Origen').val() == 0)
        $('#Origen').val("");

    $('#Fecha').datepicker();
    
    $(document).on("keypress", 'form', function (e) {
        var code = e.keyCode || e.which;
        if (code == 13) {
            e.preventDefault();
            return false;
        }
    });
    function EnviarFormulario(form) {
        $.ajax({
            type: "POST",
            url: "/Bandejas/AddOrEdit/",
            data: $(form).serialize(),
            success: function (data) {
                if (data.success) {
                    notif({
                        msg: data.mensaje,
                        type: "success",
                        position: "center"
                    });
                    $('#modalAddOrEdit').modal('hide');

                    dataTableBandejas.ajax.url('/Bandejas/ObtenerInformacion').load();
                }
                else
                    notif({
                        msg: data.mensaje,
                        type: "error",
                        position: "center"
                    });
            }
        });
    }

</script>

MVC_Produccion/Views/Bandejas/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div id="dropdownEstados" style="display:none; text-transform:capitalize">
    @Html.DropDownList("ListadoEstados", ViewBag.ListadoEstados as IEnumerable<SelectListItem>, new { @class = "form-control", @style = "text-transform: capitalize" })
</div>
<div class="col-sm-10" style="margin-left:auto;margin-right: auto;float: initial;">
    <h2>Insumos De Envio</h2>
    <table id="InicioBandejasTabla" class="display compact" style="width:100%"></table>

</div>
<!-- Modal Eliminar-->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="max-width:350px">
        <div class="modal-content">
            <div class="modal-header col-md-12" style="display:flex; justify-content:space-between">
                <h4 class="modal-title" id="exampleModalLabel">Verificación</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Está seguro desea eliminar?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="DeleteBandeja()">Confirmar</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal AddOrEdit -->
<div class="modal fade" id="modalAddOrEdit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="min-width:65%">
        <div class="modal-content" id="ModalAddOrEdit"></div>
    </div>
</div>
<!-- Modal Verificacion-->
<div class="modal fade" id="modalVerificarActualizar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="max-width:300px">
        <div class="modal-content">
            <div class="modal-header col-md-12" style="display:flex; justify-content:space-between">
                <h4 class="modal-title" id="exampleModalLabel">Verificación</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Está seguro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="ActualizarMovimientosBandejas()" data-dismiss="modal" class="btn btn-success">Confirmar</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<input type="text" hidden id="codigo"/>
<script>
    var dataTableBandejas = null;
    function CargarMovimientosBandejas() {
        dataTableBandejas = $("#InicioBandejasTabla").DataTable({
            "destroy": true,
            "autoWidth": true,
            "ajax": {
                "url": "/Bandejas/ObtenerInformacion",
                "type": "GET",
                "datatype": "json"
            },
            "columns": [
                {
                    "data": "CodigoMovimiento",
                    "title":"Codigo"
                },
                {
                    "data": "Fecha",
                    "title": "Fecha",
                    render: function (data) {
                        if (data != null) {
                            return moment(data).format('DD/MM/YYYY');
                        }
                        else {
                            return "";
                        }
                    }
                },
                {
                    "data": "Origen",
                    "title": "Origen",
                    render: function (data) {
                        return data
                    }
                },
                {
                    "data": "Destino",
                    "title": "Destino",
                    render: function (data) {
                        return data
                    }
                },
                {
                    "data": "CodigoMovimiento",
                    "title": "Herramientas",
                    "width": "10%",
                    "render": function (data) {
                        return "<a class='btn btn-default btn-sm'  onclick=AddOrEdit('" + data + "')><span class='glyphicon glyphicon-pencil'></span></a>" +
                            "<a class='btn btn-danger btn-sm' onclick=modificarInput('" + data + "') data-toggle='modal' data-target='#modalDelete'><span class='glyphicon glyphicon-trash'></span></a>";
                    },
                }

            ],
            "language": idiomaEspañol,
            dom: 'Bfrtip',
            buttons: [
                {
                    text: '<span class="glyphicon glyphicon-plus">',
                    className: 'nuevo',
                    action: function () {
                        AddOrEdit(0);
                    }
                },
                {
                    text: 'Actualizar <span class="glyphicon glyphicon-refresh">',
                    className: 'primary btn_actualizar',
                    action: function () {
                        AbrirModalActualizar();
                    }
                },
                {
                    text: $('#dropdownEstados').html(),
                    className: 'botonDropdown'
                }
            ],
            "select": 'multiple',
            "columnDefs": [
                 { className: "text-right", "targets": [0,1,2] },
                 { className: "text-center", "targets": [3] }
             ],
            "order": [[0, "asc"]],
            initComplete: function (data) {
                $('div.dataTables_filter input').focus();
                $('#dropdownEstados').html("");

                $("#ListadoEstados").change(function () {
                    console.log("changed: ", $('option:selected', this).val());
                    estado = $('option:selected', this).val();
                    if (estado == "true") {
                        $("#aclaracion").show();
                        $(".btn_actualizar").hide();
                    }
                    else {
                        $(".btn_actualizar").show();
                        $("#aclaracion").hide();
                    }

                    dataTableBandejas.ajax.url('/Bandejas/ObtenerInformacion?Historicas=' + estado).load();
                });
            }

        });
    };
    function AddOrEdit(idMov) {
        $.ajax({
            type: "GET",
            url: "/Bandejas/AddOrEdit",
            data: { idMovimiento: idMov },
            success: function (data) {
                $('#ModalAddOrEdit').html(data);
                $('#modalAddOrEdit').modal('toggle');
            }
        });
    }
    function AbrirModalActualizar() {

        var bandera = false;

        $('#InicioBandejasTabla').find('tr.selected').find('td').each(function () {
            if ($(this).index() == 0) {

                bandera = true;
            }
        });

        if (bandera == false) {
            notif({
                msg: "Por favor seleccione un registro de la tabla.",
                type: "warning",
                position: "center"
            });

            return;
        }
        else {
            $('#modalVerificarActualizar').modal('toggle');
        }

    }

    function DeleteBandeja() {
        let codigo = $("#codigo").val();
        $.ajax({
            url: "/Bandejas/Delete",
            data: { id: codigo },
            success: function (data) {
                if (data.success) {
                    notif({
                        msg: "Se elimino Correctamente",
                        type: "success",
                        position: "center"
                    });
                    $('#modalDelete').modal('hide');
                    
                    dataTableBandejas.ajax.url('/Bandejas/ObtenerInformacion').load();
                }
                else
                    notif({
                        msg: data.mensaje,
                        type: "error",
                        position: "center"
                    });
            }
        });
    }

    function modificarInput(id) {
        $('#codigo').val(id);
    }
    $(document).ready(function () {
        CargarMovimientosBandejas();
    });

    function ActualizarMovimientosBandejas() {
        let codigos = [];
        $('#InicioBandejasTabla').find('tr.selected').find('td').each(function () {
            if ($(this).index() == 0) {
                codigos.push(parseInt($(this).html()));
            }
        });
        console.log(codigos);
        $.ajax({
            type:"POST",
            url: "/Bandejas/Actualizar",
            data: { codigos: codigos },
            success: function (data) {
                if (data.success) {
                    notif({
                        msg: "Se Actualizo Correctamente",
                        type: "success",
                        position: "center"
                    });
                    $('#modalVerificarActualizar').modal('hide');

                    dataTableBandejas.ajax.url('/Bandejas/ObtenerInformacion').load();
                }
                else
                    notif({
                        msg: data.mensaje,
                        type: "error",
                        position: "center"
                    });
            }
        });
    }
</script>

MVC_Produccion/Views/Bandejas/TablaBandejas.cshtml
@using AccesoDatos.Contexto.Produccion
@model List<DetallesMovimientosBandejas>
@{
    Layout = null;
}
<table id="TablaBandeja" class="display compact" style="width:100%">
    <thead>
        <tr>
            <th colspan="2" style="width:150px;">Insumos De Envio</th>
            <th style="width:100px;">Unidades</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (!ViewBag.soloLectura)
        {
            <tr style="padding-top:5px;">
                <td style="width:10%;">
                    <div id="Div_Insumo">
                        <div class="input-group">
                            <input type="text" id="Codigo_Insumo" name="Codigo_Insumo" class="form-control" />
                            <span class="input-group-addon"><a href="#" onclick="AbrirModalInsumos()"><span class="glyphicon glyphicon-search"></span></a></span>
                        </div>
                    </div>
                </td>
                <td id="descripcion-insumo" style="width:50%;"></td>
                <td>
                    <input class="form-control text-box single-line" id="Unidades" type="number" placeholder="Unidades" style="text-align:right;padding:10px 10px !important;" />
                </td>
                <td style="text-align:right;">
                    <button type="button" class="btn btn-success btn-sm" onclick="ExisteInsumo(true);"><span class="glyphicon glyphicon-ok"></span></button>
                </td>
            </tr>
        }
        @{ foreach (var item in Model)
            {
        <tr class="tr-bandeja">
            <td id="td-codigo-insumo">@item.Codigo_Insumo<input hidden id="input-codigo-insumo" value="@item.Codigo_Insumo"></td>
            <td id="td-desc-insumo">@item.Insumo.Descripcion</td>
            <td id="td-unidades" style="padding:5px 10px !important;text-align:right;">@item.Unidades<input hidden id="input-unidades" value="@item.Unidades"></td>
            @if (!ViewBag.soloLectura)
            {
                <td style="text-align:right;"><a class="btn btn-danger btn-sm" onclick="BorrarBandeja($(this));"><span class="glyphicon glyphicon-trash"></span></a></td>
            }
        </tr>
            }
        }
    </tbody>
</table>
<script>
    $("#Codigo_Insumo").change(function () {
        ExisteInsumo(false);
    });

    ActualizarName();
    function ExisteInsumo(agregar) {
        let codigo = $("#Codigo_Insumo").val();
        if (!codigo) {
            return
        }
        $.ajax({
            type: "GET",
            url: "/Insumos/GetOne/",
            data: {
                Codigo_Insumo: codigo
            },
            success: function (data) {
                if (data.success) {
                    let insumo = data.data[0];
                    $("#descripcion-insumo").html(insumo.Descripcion);
                    if (agregar) {
                        AgregarBandeja();
                    }
                    return
                }
                else {
                    notif({
                        msg: "No existe el insumo",
                        type: "error",
                        position: "center"
                    });
                    $("#Codigo_Insumo").focus();
                    return true;
                }
            }
        });
    }

    function AgregarBandeja() {
        if ($('#Unidades').val() <= 0) {
            alert("Las unidades deben ser Mayor a 0");
            return
        }

        let fila = '';
        fila = '<tr class="tr-bandeja">';
        fila += '<td id="td-codigo-insumo">' + $("#Codigo_Insumo").val() + '<input hidden id="input-codigo-insumo" value=' + $("#Codigo_Insumo").val() + '></td>';
        fila += '<td id="td-desc-insumo">' + $("#descripcion-insumo").html() + '</td>';
        fila += '<td id="td-unidades" style="padding:5px 10px !important;text-align:right;">' + $('#Unidades').val() + '<input hidden id="input-unidades" value=' + $('#Unidades').val()+'></td>';
        fila += '<td style="text-align:right;"><a class="btn btn-danger btn-sm" onclick ="BorrarBandeja($(this));"><span class="glyphicon glyphicon-trash"></span></a></td>';
        fila += '</tr>';
        $('#TablaBandeja tbody').append(fila);
        $('#Unidades').val("");
        $("#Codigo_Insumo").val("");
        $("#descripcion-insumo").html("");
        ActualizarName();
        $("#Codigo_Insumo").focus();

    }

    function BorrarBandeja(td) {
        $(td).parent().parent().remove();
        ActualizarName();

    }

    function ActualizarName() {
        let nombre = '@ViewBag.parametroPost';
        $("#TablaBandeja tbody .tr-bandeja").each(function (i, item) {
            $(this).find("#input-codigo-insumo")[0].setAttribute("name", `${nombre}[${i}].Codigo_Insumo`);
            $(this).find("#input-unidades")[0].setAttribute("name", `${nombre}[${i}].Unidades`);
        });
    }

</script>