MVC_Produccion/Controllers/LocalidadesController.cs
using AccesoDatos.Contexto.Ventas;
using Servicios.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace MVC_Produccion.Controllers
{
    public class LocalidadesController : Controller
    {
        private IBaseServicio<Localidades> LocalidadesServicio;
        private IBaseServicio<Provincias> ProvinciasServicio;

        public LocalidadesController(IBaseServicio<Localidades> localidadesServicio,
                                    IBaseServicio<Provincias> provinciasServicio)
        {
            this.ProvinciasServicio = provinciasServicio;
            this.LocalidadesServicio = localidadesServicio;
        }

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ObtenerProvincias()
        {
            var listado = this.ProvinciasServicio.Obtener().Select(p => new {
                Nro_Provincia =  p.Nro_Provincia,
                Descripcion =  p.Descripcion
            });

            return Json(new
            {
               listado =  listado
            }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult Obtener()
        {
            var listado = this.LocalidadesServicio.Obtener().Select(l => new {
                l.CODIGO,
                l.DESCRIPCION,
                l.PREFIJO,
                l.PROVINCIA
            });

            return Json(new
            {
                success = true,
                mensaje = "",
                listado = listado
            }, JsonRequestBehavior.AllowGet);
        }

        // GET: Localidades/Create
        public ActionResult addOrEdit(string codigo = "")
        {
            bool agregar = false;
            var localidad = this.LocalidadesServicio.Obtener((l) => l.CODIGO == codigo).SingleOrDefault();
            if (localidad == null)
            {
                localidad = new Localidades() {CODIGO = (this.LocalidadesServicio.Obtener().Count + 1).ToString() };
                agregar = true;
            }
            ViewBag.agregar = agregar;

            return View(localidad);
        }

        // POST: Localidades/Create
        [HttpPost]
        public ActionResult addOrEdit(Localidades model,bool agregar)
        {
            using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    if (model.PROVINCIA != null && model.PROVINCIA != "")
                        model.PROVINCIA = model.PROVINCIA.Trim();
                    if (agregar)
                        this.LocalidadesServicio.Agregar(model);
                    else
                        this.LocalidadesServicio.Editar(model);
                    scope.Complete();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.agregar = agregar;
                    ModelState.AddModelError("", ex.Message);

                    return View(model);
                }
            }
        }

        // POST: Localidades/Delete/5
        [HttpPost]
        public ActionResult Delete(string codigo)
        {
            using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    var elminar = this.LocalidadesServicio.Obtener((l) => l.CODIGO == codigo).SingleOrDefault();
                    if (elminar != null)
                    {
                        this.LocalidadesServicio.Borrar(elminar);
                        scope.Complete();
                        return Json(new
                        {
                            success = true,
                            message = "Se elimino Correctamente",
                        }, JsonRequestBehavior.AllowGet);
                    }
                    else
                        return Json(new
                        {
                            success = false,
                            message = "No se encontro Localidad",
                        }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json(new
                    {
                        success = false,
                        message = ex.Message,
                    }, JsonRequestBehavior.AllowGet);
                }
            }
        }
    }
}

MVC_Produccion/Views/Localidades/AddOrEdit.cshtml
@model AccesoDatos.Contexto.Ventas.Localidades
@{
    if (Model.CODIGO == "")
    {
        ViewBag.Title = "Localidad : Nuevo";
    }
    else
    {
        ViewBag.Title = "Localidad : Editar";
    }

}

@using (Html.BeginForm("AddOrEdit", "Localidades", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="col-md-12 contenedor-formulas-add">
        <div class="col-md-12 flexible2">
                @if (ViewBag.agregar)
                {
                    <input type="text" hidden value="true" name="agregar" />
                }
                else
                {
                    <input type="text" hidden value="false" name="agregar" />
                }

            <div class="col-md-12 caja-contenedora" style="padding-bottom:0px !important">
                <div class="col-md-12 caja-sector">
                    <div class="col-md-3 form-medio">
                        <div class="col-md-3 form-medio">
                            @Html.LabelFor(model => model.CODIGO, "Codigo:", new { @class = "control-label" })
                        </div>
                        <div class="col-md-3 form-medio">
                            <div class="input-group">
                                @if (ViewBag.agregar)
                                {
                                    <input type="text" hidden value="true" name="agregar" />
                                    @Html.EditorFor(model => model.CODIGO, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                                }
                                else
                                {
                                    @Html.EditorFor(model => model.CODIGO, new { htmlAttributes = new { @class = "form-control", @type = "text", readOnly="readOnly" } })
                                    <input type="text" hidden value="false" name="agregar" />
                                }
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7 form-medio">
                        <div class="col-md-2 form-medio">
                            @Html.LabelFor(model => model.DESCRIPCION, "Descripcion:", new { @class = "control-label" })
                        </div>
                        <div class="col-md-6 form-medio">
                            @Html.EditorFor(model => model.DESCRIPCION, new { htmlAttributes = new { @class = "form-control", @type = "text", @required = "true" } })

                        </div>
                    </div>
                    <div class="col-md-3 form-medio">
                        <div class="col-md-6 form-medio">
                            @Html.LabelFor(model => model.PREFIJO, "Prefijo Telefónico:", new { @class = "control-label" })
                        </div>
                        <div class="col-md-6 form-medio">
                            @Html.EditorFor(model => model.PREFIJO, new { htmlAttributes = new { @class = "form-control", @type = "text" } })

                        </div>
                    </div>
                </div>
                <div class="col-md-12 caja-sector">
                    <div class="col-md-3 form-medio">
                        <div class="col-md-3 form-medio">
                            @Html.LabelFor(model => model.PROVINCIA, "Provincia:", new { @class = "control-label" })
                        </div>
                        <div class="col-md-5 form-medio">
                            <div class="input-group">
                                @Html.EditorFor(model => model.PROVINCIA, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                                <span class="input-group-addon"><a href="#" onclick="AbrirModalProvincias('PROVINCIA')"><span class="glyphicon glyphicon-search"></span></a></span>
                            </div>
                            @Html.ValidationMessageFor(model => model.PROVINCIA)
                        </div>
                    </div>
                </div>

            </div>
            <!-- CONTENEDOR SUBMIT-->

            <div class="col-md-12 flexible">
                <div class="col-md-12 contenedor-btns-form">
                    <div class="form-group" style="margin:0px !important">
                        <button class="btn btn-primary" id="btn_ConfirmarFormulario" type="submit">Confirmar</button>
                        <a class="btn btn-default" href="@Url.Action("Index", "Localidades")">Volver</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>
    function ConfirmarCodigoComprobante() {
        $('#ComprobantesTabla').find('tr.selected').find('td').each(function () {
            if ($(this).index() == 0) {

                $('#Codigo_Comprob').val($(this).html());
            }
        });

        $('#modalCodigosComprobantes').modal('hide');
    }


    function MostrarMensaje(mensaje, tipo) {
        notif({
            msg: mensaje,
            type: tipo,
            position: "center"
        });
    };



    $(function () {

        if ("@ViewBag.error" != "") {
            MostrarMensaje("@ViewBag.error", "error");
        }


        $('#modalCodigosComprobantes').on('shown.bs.modal', function (e) {
            $('#ConfirmarComprobante').click(function () {
                ConfirmarCodigoComprobante();
            });

            $('#ComprobantesTabla tbody').on('click', 'tr.selected', function () {

                ConfirmarCodigoComprobante();

            });
        });
    });
</script>

MVC_Produccion/Views/Localidades/Index.cshtml
@{
    ViewBag.Title = "Localidades : Listado";
}

<h2>Localidades</h2>

<table id="LocalidadesTablaIndex" class="display compact" style="width:100%"></table>

<!-- Modal Eliminar-->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header col-md-12" style="display:flex; justify-content:space-between">
                <h4 class="modal-title" id="exampleModalLabel">Verificación</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Está seguro desea eliminar?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="DeleteLocalidad()">Confirmar</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>


<input  id="codigo_localidad_eliminar" hidden />

@section scripts{
    <script>
        var ListadoLocalidades = []

        function CargarLocalidadesIndex() {
            $.ajax({
                type: "GET",
                url: "/Localidades/Obtener",
                success: function (data) {
                    ListadoLocalidades = [];
                    if (data.success) {
                        $.each(data.listado, function (i, item) {
                            ListadoLocalidades.push(item);
                        });
                    }
                },
                complete: function (data) {
                    CargarLocalidadesTabla();
                }

            });
        }


        function CargarLocalidadesTabla() {
            dataTable = $("#LocalidadesTablaIndex").DataTable({
                "destroy": true,
                "autoWidth": true,
                data : ListadoLocalidades,
                "columns": [
                    {
                        "data": "CODIGO",
                        "title": "Código",
                        "width": "10%"
                    },
                    {
                        "data": "DESCRIPCION",
                        "title": "Descripcion",
                        render: function (data) {
                            if (data != null) {
                                return data;
                            }
                            else {
                                return "";
                            }
                        }
                    },
                    {
                        "data": "PROVINCIA",
                        "title": "Provincia",
                        render: function (data) {
                            if (data != null) {
                                return data;
                            }
                            else {
                                return "";
                            }
                        }
                    },
                    {
                        "data": "PREFIJO",
                        "title": "Prefijo",
                        render: function (data) {
                            if (data != null) {
                                return data;
                            }
                            else {
                                return "";
                            }
                        }
                    },
                    {
                        "data": "CODIGO",
                        "title": "",
                        "width": "10%",
                        "render": function (data) {
                            return "<a class='btn btn-default btn-sm' href='/Localidades/AddOrEdit/?codigo=" + data + "'><span class='glyphicon glyphicon-pencil'></span></a>" +
                                    `<a class='btn btn-danger btn-sm' onclick="modificarInput('${data}')" data-toggle='modal' data-target='#modalDelete'><span class='glyphicon glyphicon-trash'></span></a>`;
                        },
                    }

                ],
                "language": idiomaEspañol,
                dom: 'Bfrtip',
                buttons: [
                   {
                       text: '<span class="glyphicon glyphicon-plus">',
                       className: 'nuevo',
                       action: function () {
                           window.location.href = "/Localidades/AddOrEdit/";
                       }
                   },
                ],
                "select": 'multiple',
                "columnDefs": [
                      { className: "text-left", "targets": [1,2] },
                      { className: "text-center", "targets": [0, 3] },
                      { className: "text-right", "targets": [4] },

                ],
                "order": [[0, "asc"]],
                initComplete: function (data) {
                    $('div.dataTables_filter input').focus();
                }

            });

        };

        function MostrarMensaje(mensaje, tipo) {
            notif({
                msg: mensaje,
                type: tipo,
                position: "center"
            });
        };



        function modificarInput(Codigo_Compra) {
            console.log(Codigo_Compra);
            $('#codigo_localidad_eliminar').val(Codigo_Compra);
        }

        /*ELIMINA UNA FÓRMULA*/

        function DeleteLocalidad() {
            $.ajax({
                type: "POST",
                url: "/Localidades/Delete/",
                data: { codigo: $('#codigo_localidad_eliminar').val() },
                success: function (data) {
                    if (data.success) {
                        $('#modalDelete').modal('hide');

                        notif({
                            msg: data.message,
                            type: "success",
                            position: "center"
                        });

                        CargarLocalidadesIndex();

                    }
                    else {
                        notif({
                            msg: data.message,
                            type: "error",
                            position: "center"
                        });
                        console.log("ERROR: " + data.consola);
                    }
                }
            });

        };

        $(document).ready(function () {

            CargarLocalidadesIndex();

            if ("@ViewBag.Resultado" != "") {
                MostrarMensaje("@ViewBag.Resultado", "success");
            }

            if ("@ViewBag.error" != "") {
                MostrarMensaje("@ViewBag.error","error");
            }
        });
    </script>
}